# Generated by Django 6.0.3 on 2026-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarypage',
            options={'ordering': ['-written_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='diarypage',
            old_name='date',
            new_name='written_date',
        ),
        migrations.AddField(
            model_name='diarypage',
            name='search_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
