# Generated by Django 6.0.3 on 2026-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_diarypage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarypage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='diarypage',
            name='title',
        ),
        migrations.AddField(
            model_name='diarypage',
            name='page',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diarypage',
            name='written_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
